version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: gablab-swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - URL=artcoded.net
      - SUBDOMAINS=lab
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      - EMAIL=mail.artcoded@gmail.com
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=false #optional
    volumes:
      - ./swag:/config/nginx/site-confs
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  jenkins:
    image: jenkins/jenkins
    container_name: gablab-jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
    restart: unless-stopped
  registry:
    image: registry
    container_name: gablab-docker
    ports:
      - 5000:5000
    volumes:
      - ./docker:/var/lib/registry
    restart: unless-stopped
