version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: v-delizie-swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - URL=cleverup.net
      - SUBDOMAINS=lab
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      - EMAIL=mail.cleverup@gmail.com
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=false #optional
    volumes:
      - ./swag:/config/nginx/site-confs
    ports:
      - 443:443
      - 80:80 #optional

  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - PASSWORD=88Gab.12 #optional
      - SUDO_PASSWORD=88Gab.12 #optional
      - PROXY_DOMAIN=lab.cleverup.net #optional
    volumes:
      - ./code-server:/config
    ports:
      - 8443:8443
    restart: unless-stopped